# This is a basic workflow to help you get started with Actions
# Separating the runner by tag [dev_staging, production]

name: Malware scanning

# Controls when the workflow will run
on:
  # Triggers the workflow on  pull request events but only for the main branch
  push:
    # Apply on to those branches (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches)
    branchs: [clamav-defaultdb]

docker pull clamav/clamav:latest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clamAV:
    runs-on: ubuntu-latest
    container:
      image: clamav/clamav:latest
    steps:
      - name: Checkout main backend repo
        uses: actions/checkout@v2
      - name: scanning with clamAV
        run: |
          clamscan .